#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

ROOT=_output/Kotlin.docset
RESOURCES=$ROOT/Contents/Resources

rm -rf $ROOT
mkdir -p $RESOURCES

cp src/Info.plist $ROOT/Contents/
cp -r _input $RESOURCES/Documents
cat src/overrides.css >> $RESOURCES/Documents/css/styles.css

mkdir -p _tmp
convert src/icon.png -resize 16x16 _tmp/icon.png
convert src/icon.png -resize 32x32 _tmp/icon@2x.png
tiffutil -cathidpicheck _tmp/icon.png _tmp/icon@2x.png -out $ROOT/icon.tiff

cat src/setup.sql | sqlite3 $RESOURCES/docSet.dsidx

pushd _input
find . -name \*\.html | xargs -n1 -P4 ruby ../src/index.rb | sqlite3 ../$RESOURCES/docSet.dsidx
popd

cd _output
tar \
  --exclude 'tutorials.*' \
  --exclude 'apple-touch-*.png' \
  --exclude='.DS_Store' \
  -cvzf Kotlin.tgz \
  Kotlin.docset
