#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

install() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    if ! hash brew 2>/dev/null; then
      echo "Please install homebrew from http://brew.sh/"
      exit 1
    fi
  fi

  read -p "Install $1 now? [y/N] " -n 1 -r
  echo

  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Exiting..."
    exit 1
  fi

  echo "Installing $1..."
  ./pacapt -S $1
}

check() {
  if ! hash $1 2>/dev/null; then
    echo "Couldn't find dependency: $1"
    install ${2:-$1}
  fi
}

check wget
check convert imagemagick

./fetch && ./generate
