#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

mkdir -p _input
cd _input

FILES=(
  "_assets/default.js"
  "_assets/common.js"
  "_assets/common.css"
  "_assets/styles.css"
)

for f in ${FILES[@]}
do
  dir=`dirname $f`
  mkdir -p $dir
  wget -O $f http://kotlinlang.org/$f
done

wget --mirror --reject-regex 'api/latest/jvm/stdlib/org' -k -nH http://kotlinlang.org/docs/reference/

wget -O - https://github.com/JetBrains/kotlin/archive/gh-pages.zip | bsdtar -xvf-
mv kotlin-gh-pages _javadoc
