#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

ROOT=_output/Kotlin.docset
RESOURCES=$ROOT/Contents/Resources

rm -rf $ROOT
mkdir -p $RESOURCES

cp src/Info.plist $ROOT/Contents/
cp -r _input $RESOURCES/Documents
cat src/overrides.css >> $RESOURCES/Documents/_assets/styles.css
cat src/overrides.css >> $RESOURCES/Documents/_assets/common.css

mkdir -p _tmp

if hash tiffutil 2>/dev/null; then
  convert src/icon.png -resize 16x16 _tmp/icon.png
  convert src/icon.png -resize 32x32 _tmp/icon@2x.png
  tiffutil -cathidpicheck _tmp/icon.png _tmp/icon@2x.png -out $ROOT/icon.tiff
fi

cat src/setup.sql | sqlite3 $RESOURCES/docSet.dsidx

pushd _input
find . -name \*\.html | xargs -n1 -P4 ruby ../src/index.rb | sqlite3 ../$RESOURCES/docSet.dsidx
popd

pushd _output
tar \
  --exclude 'tutorials.*' \
  --exclude 'apple-touch-*.png' \
  --exclude='.DS_Store' \
  -cvzf Kotlin.tgz \
  Kotlin.docset
popd

if [ ! -f $ROOT/icon.tiff ]; then
  echo "Warning: Couldn't generate icon.tiff for retina display support!"
  echo "Do NOT submit this to https://github.com/Kapeli/Dash-User-Contributions"
  exit 1
fi
